### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'runDynamic' 

### ISSUE THREAD

**Issue by ProG4mr** [frabbit/angular.haxe#6]
Creating a small module using this code:

```haxe
var myApp = Angular.module('myApp', []);
myApp.run(function(s:TemplateCache) {
	s.put('test', 'hahahhhhahahaha');
});
```

produces the following js:

```js
myApp.runDynamic(["$templateCache",function(s) {
    s.put("test","hahahhhhahahaha");
}]);
```

which produces the error:
```Uncaught TypeError: Object #<Object> has no method 'runDynamic' ```

Any clue why this is happening? Using git version of angular.haxe and angular 1.3.12.

**Comment by frabbit** [comment]
The library requires latest builds of the compiler.

**Comment by frabbit** [comment]
i will close this issue, feel free to reopen if you have also problems with latest builds.
