### ISSUE TITLE
controllerDynamic is used instead of controller

### ISSUE THREAD

**Issue by remcohuijser** [frabbit/angular.haxe#8]
I am really looking forward to working with Haxe and Angular, but I currently have the problem that the following code:
var module = Angular.module("myModule", [])
            .factory(Config.new)
            .controller("AppController", appController);

Is compiled into:
var module = window.angular.module("myModule",[]).factoryDynamic("Config",[function() {
		return new Config();
	}]).controllerDynamic("AppController",["$scope","Config",appController]);

Even though the methods are marked with for example:
@:noCompletion @:native("controller") public function controllerDynamic (name:String, value:Dynamic):Module;

It seems the @:native is not used.
Did anyone else run into this problem?
I am using Haxe 3.1.3

**Comment by frabbit** [comment]
sorry, i didn't saw this issue. The library does only work with 3.2 which was released some weeks ago.
